### PR TITLE
moved convars to F1 menu

### PR DESCRIPTION
**Pull request by mexikoedi**
Moved convars from ULX to the F1 menu.
Tested and it seemed to work fine.
I hope I didn't forget anything.
The labels should be looked at, maybe they need to be adjusted.

### CODE REVIEW

**Comment by mexikoedi** [comment]
Could you review/merge this PR and update your role if you have time @Gensokian ?
Should work fine.

**Comment by Gensokian** [comment]
@mexikoedi Thanks a bunch! Not too active on TTT lately because of personal things. Will update on WS as soon as I can.

**Comment by mexikoedi** [comment]
> @mexikoedi Thanks a bunch! Not too active on TTT lately because of personal things. Will update on WS as soon as I can.

It has been a while.
Do you have time for an update?
@Gensokian

**Comment by mexikoedi** [comment]
@Gensokian 
I don't want to be annoying but it would be very nice if it could get updated.
I could also assist with the updating process if you give the permissions on the Steam Workshop.
Then I could update it in the coming days.

**Pull request merged**
